---
version: 2
project_name: enduro-sdps

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^website:'

builds:
- env:
  - CGO_ENABLED=0
  id: enduro
  goos:
  - linux
  goarch:
  - amd64
  flags:
  - -trimpath
  ldflags:
  - -X "main.buildTime={{.Date}}"
  - -X "main.gitCommit={{.Commit}}"
  - -X "main.version={{.Version}}"
  main: ./cmd/enduro
  binary: enduro

- env:
  - CGO_ENABLED=0
  id: enduro-am-worker
  goos:
  - linux
  goarch:
  - amd64
  flags:
  - -trimpath
  ldflags:
  - -X "main.buildTime={{.Date}}"
  - -X "main.gitCommit={{.Commit}}"
  - -X "main.version={{.Version}}"
  main: ./cmd/enduro-am-worker
  binary: enduro-am-worker

- env:
  - CGO_ENABLED=0
  id: enduro-a3m-worker
  goos:
  - linux
  goarch:
  - amd64
  flags:
  - -trimpath
  ldflags:
  - -X "main.buildTime={{.Date}}"
  - -X "main.gitCommit={{.Commit}}"
  - -X "main.version={{.Version}}"
  main: ./cmd/enduro-a3m-worker
  binary: enduro-a3m-worker


archives:
- wrap_in_directory: true
  format: tar.gz
  name_template: >-
    {{ .ProjectName }}_
    {{- .Version }}_
    {{- title .Os }}-
    {{- if eq .Arch "amd64" }}64bit
    {{- else if eq .Arch "386" }}32bit
    {{- else }}{{ .Arch }}{{ end }}
  files:
  - LICENSE
  - README.md
  - enduro.toml

checksum:
  name_template: checksums.txt
  algorithm: sha256
